[package]
name = "meetuprsvp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }

chrono = { version = "0.4", features = ["serde"] }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

